base_url = "https://dev.flare.network/"
user_agent = "curl/8.7.1"
verbose = "info"
no_progress = true
cache = true
max_cache_age = "2d"
cache_exclude_status = ["..100", "403", "429", "500.."]
timeout = 30
retry_wait_time = 2
max_retries = 3
max_concurrency = 8
accept = ["200..=399", "429"]
exclude_all_private = true
exclude = [
    '^https://dev\.flare\.network/',
    '^https://fdc-verifiers-testnet\.flare\.network/',
    '^https://github\.com/flare-foundation/flare-hardhat-starter/',
    '^https://github\.com/flare-foundation/flare-foundry-starter/',
    '^https://sepolia\.etherscan\.io/',
    '^https://metamask\.io/',
    '^https://openweathermap\.org/',
    '^https://www\.gnu\.org/',
    '^https://swapi\.dev/',
    '^https://www\.npmjs\.com/',
    '^https://discord\.com/',
    '^https://docs\.eigencloud\.xyz/',
    '^https://coston2\.testnet\.flarescan\.com/',
    '^https://jq-verifier-test\.flare\.rocks',
]
