blank_issues_enabled: false
contact_links:
  - name: General questions - Discord
    url: https://discord.com/invite/flarenetwork
    about: Please ask your general questions on Discord (#ğŸ”¶â”‚ğ˜‰ğ˜œğ˜ğ˜“ğ˜‹ers-onlyğŸ’ªğŸ» channel).
